### ISSUE TITLE
Request - generate password from character set

### ISSUE THREAD

**Issue by bartreardon** [joshua-d-miller/macOSLAPS#1]
as per the title - can we have a random password generated from a given set. It's not obvious (or easy) to say remove all non alphanumeric characters if, for example, it's determined that [a-z][1-9] is sufficient for requirements.

The idea here would be a seperate key from RemovePassChars, perhaps called LimitPassChars.

**Comment by joshua-d-miller** [comment]
Thank you for this suggestion. I have gone ahead and released a new version of macOSLAPS with the new key **ExclusionSets**. Give it a try and let me know! 👍

**Comment by bartreardon** [comment]
looks good - I'll give it a go, thanks :)

**Comment by joshua-d-miller** [comment]
Did this work for you?

**Comment by bartreardon** [comment]
sorry for not getting back earlier - works well 👍

**Comment by joshua-d-miller** [comment]
Thank you for the update :)
