### ISSUE TITLE
Feature Request - reset password independent of password reset date

### ISSUE THREAD

**Issue by bartreardon** [joshua-d-miller/macOSLAPS#10]
New feature request:

In instances when a mac has been re-built, macOSLAPS won't update the local admin account password if the expiry date stored in AD has not been reached yet. This means the password as stored in AD will not be in sync with what is actually on the machine. It would be hand to be able to run the tool with a switch to update the password at any time, specifically for re-builds (e.g. it could run after rebuild to re-sync the local password with what's in AD).

If I get the chance I'll take a look at the code and issue a PR - documenting here for feedback.

**Comment by joshua-d-miller** [comment]
Thank you for the feature request. I have posted a new build which takes command line arguments. You should be able to call macOSLAPS from the command line with the argument **-resetPassword**. Let me know if it works for you! 👍

**Comment by bartreardon** [comment]
that works well - thank you :)

**Comment by joshua-d-miller** [comment]
Glad to hear it. I'll be closing this issue 👍
