### ISSUE TITLE
Migrating to Jamf LAPS

### ISSUE THREAD

**Issue by fgs2022** [joshua-d-miller/macOSLAPS#101]
Hello,

What is the best practice to transition from macOSLAPS to the new Jamf Pro LAPS solution? Thanks.

https://learn.jamf.com/bundle/technical-paper-laps-current/page/Local_Administrator_Password_Solution.html

**Comment by joshua-d-miller** [comment]
So based on their documentation they use the second admin account you create with a PreStage enrollment. If your admin you are using for macOSLAPS **is not** this account then you should most likely be fine but it also means most likely just new machines going forward.

I would probably say if you plan to transition to Jamf's implementation that you would keep macOSLAPS on older devices and use Jamf's implementation on new ones for the smoothest transition. Not ideal for admins but probably best. Just my opinion though.

**Comment by fgs2022** [comment]
Thanks. Is removal of the items below still the preferred method to uninstall macOSLAPS?

https://github.com/joshua-d-miller/macOSLAPS/issues/13

**Comment by fgs2022** [comment]
I was able to remove macOSLAPS and migrate to the Jamf LAPS solution.
