### ISSUE TITLE
Uninstall 

### ISSUE THREAD

**Issue by kadeemcallum** [joshua-d-miller/macOSLAPS#13]
What is the process for uninstallation of the macOSLAPS?

**Comment by joshua-d-miller** [comment]
@kadeemcallum Are you using a software deployment utility? I use munki and it naturally knows how to remove anything a package installs. If you wanted to remove it manually however you would need to remove the following files which I believe could also be scripted:

/etc/paths.d/laps
/Library/LaunchDaemons/edu.psu.macoslaps-check.plist
/usr/local/laps/macOSLAPS

I'd also add you should probably change the password back to something else and remove it from the AD Computer Record.

**Comment by kadeemcallum** [comment]
Thanks!
