### ISSUE TITLE
Not working on 10.13.3

### ISSUE THREAD

**Issue by TheGunslingerRG** [joshua-d-miller/macOSLAPS#15]
There isn't a whole lot of information other than the logs I have right now however when macOSLAPS runs on a 10.13.3 machine it does change the local admin password but never writes back to AD.

Info|Thu Feb 22, 2018 09:57:08 AM|macOSLAPS|Password Change is required as the LAPS password for admin has expired
Warning|Thu Feb 22, 2018 09:57:09 AM|macOSLAPS|There was an error setting the password for this device...
Warning|Thu Feb 22, 2018 09:57:09 AM|macOSLAPS|There was an error setting the new password expiration for this device...
Info|Thu Feb 22, 2018 09:57:09 AM|macOSLAPS|Password change has been completed for local admin admin. New expiration date is Mon Apr 23, 2018 09:57:09 AM
Info|Thu Feb 22, 2018 09:57:09 AM|macOSLAPS|Removing Keychain for local administrator account admin...

We don't have this issue on other versions of the OS on campus and have it running successfully on almost 1000 machines.

**Comment by briend** [comment]
Have you tried the python version (macOSLAPS-legacy) to see if that makes a difference?

**Comment by TheGunslingerRG** [comment]
Well, in the end we got it to work. When the Pythin version didn't work we thought something was up. We unbound/rebound after making sure the share name and bind name matched and it started working as we expected. Don't know exactly what happened but I imagine that there's something in the bind. We have a few others with the same issue but I bet we can make those work as well now that we know it can work. 

Sorry for the alarm!

**Comment by joshua-d-miller** [comment]
No worries on the alarm. I'm glad you got it sorted out. I'll go ahead and close this issue.
