### ISSUE TITLE
paths.d/laps

### ISSUE THREAD

**Issue by kadeemcallum** [joshua-d-miller/macOSLAPS#19]
Hi Joshua,

I am trying to implement the macOSLAPS into my environment. Minor changes needed to be made to the source code to meet environment requirements.
Using the application Packages I am now trying to repackage the macOSLAPS application. Unfortunately the `sudo macoslaps` command receives this error: `sudo: macoslaps: command not found`. 

Is there any way to fix this for implementation?
_Attached is a screenshot of the package I created. It is not working from your source code_
Thanks

<img width="908" alt="screen shot 2018-05-04 at 12 21 23 pm" src="https://user-images.githubusercontent.com/24302179/39643549-1b6375de-4fa3-11e8-910f-f7eb5a2bfde0.png">

**Comment by bartreardon** [comment]
hey @kadeemcallum - presuming everything else is ok (paths.d file has a line for /usr/local/laps") the command is case sensitive, so you need to type `macOSLAPS` not `macoslaps`
