### ISSUE TITLE
Error when building from Xcode 8.3.3

### ISSUE THREAD

**Issue by rhs615** [joshua-d-miller/macOSLAPS#2]
When trying to build with Xcode 8.3.3, I get the following error:

![screenshot 2017-07-13 14 07 54](https://user-images.githubusercontent.com/1043255/28180950-e17b0e7e-67d4-11e7-9cf7-06b200d8694d.png)

Any thoughts?

**Comment by joshua-d-miller** [comment]
I just did some testing with 8.3.3 and the latest version from this repo and the build was successful. I'm not sure why you are receiving that error. Would you be able to reclone the repo and give that a try?

**Comment by joshua-d-miller** [comment]
If you are still having this issue please let me know otherwise I'll be closing this issue.
