### ISSUE TITLE
plist file

### ISSUE THREAD

**Issue by nathantkelley** [joshua-d-miller/macOSLAPS#20]
What is the format of the .plist file?  Just match syntax in ConfigSettings.swift?  Example different local admin name with 1 day password expiry.  We have the latest release package working fine.  Just need to understand how to customize and if simply creating this file and placing at /Libary/Preferences/edu.psu.macoslaps.plist will get detected next time the daemon runs?

Also and advice for removing the Penn State branding?

**Comment by briend** [comment]
There's an example in the python version:
https://github.com/joshua-d-miller/macOSLAPS-Legacy/blob/master/edu.psu.macoslaps.plist
but I do think an example should be provided for the new version too

**Comment by nathantkelley** [comment]
This worked for me.  Thanks!

**Comment by joshua-d-miller** [comment]
Plist example file has been copied to this repository. Thank you!
