### ISSUE TITLE
...or the domain controller is not writable

### ISSUE THREAD

**Issue by betorivas** [joshua-d-miller/macOSLAPS#24]
Hi Joshua,

We are getting this error when macoslaps runs, and I think is because the offices our Macs are located in all have Read Only Domain controllers, is there a way to specify which domain controller to use?

Thanks.

**Comment by joshua-d-miller** [comment]
Hi @betorivas,

I was wondering if you could set the preferred domain server in your AD Settings manually and see if that resolves the issue? I'm currently exploring setting this option temporarily when launching macOSLAPS.

Thanks!

**Comment by joshua-d-miller** [comment]
@betorivas Please try the attached prebuild of macOSLAPS and specify a DC as a string under the PreferrredDC key. Let me know if it works.

**Comment by betorivas** [comment]
Thank you very much!

Will try tomorrow and reply back right away!

**Comment by betorivas** [comment]
just tried running it and it only says "Killed: 9", with our without the
new key.
I even tested PreferrredDC and PreferredDC in case the key had an extra R
typo.

**Comment by joshua-d-miller** [comment]
So it just crashed? Did you type in the FQDN of the writable domain controller? I just tested with my FQDN controlelr and it seemed to work. Key is **PreferredDC** and the value should be a **string** so **servername.domain.local**

**Comment by betorivas** [comment]
Yup, FQDN.
Not sure if I "installed" correctly, since I simply replaced the old binary
with this new one and edited the plist.

**Comment by joshua-d-miller** [comment]
Try this file attachment [macOSLAPS.zip](https://github.com/joshua-d-miller/macOSLAPS/files/2687532/macOSLAPS.zip) and hopefully you have better luck. If you don't can you send me a log of the output if any?

**Comment by joshua-d-miller** [comment]
@betorivas Please try the latest build and specify the **PreferredDC** key and let me know if it works for you.

**Comment by betorivas** [comment]
Thanks will do!

**Comment by joshua-d-miller** [comment]
@betorivas The latest build has a fix as it was determined that on a newly bound machine the date would be invalid so our check to see if the DC is writable would always fail. I have gone ahead and updated this so please try the new build and let me know!

**Comment by joshua-d-miller** [comment]
I am going to call this issue resolved as well as we determined a newly bound machine would have an invalid date and would always fail the date set so this has been corrected.

**Comment by betorivas** [comment]
Sorry I didnt reply before. It works perfectly!
