### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by macadmin1** [joshua-d-miller/macOSLAPS#28]
Took me a while to figure out why copy pasting this path wasn't working.

`Libary` should be `Library`

`These parameters are set in the location /Libary/Preferences/edu.psu.macoslaps.plist or you can use your MDM's Custom Settings to set these values.`

**Comment by joshua-d-miller** [comment]
Hi there,

Thank you for this. I have addressed the typo.

Thanks again!
