### ISSUE TITLE
Local admin password not changing

### ISSUE THREAD

**Issue by ffxsup** [joshua-d-miller/macOSLAPS#29]
Successfully installed macOSLAPS and seeing successfully writing of random password in AD ms-Mcs-AdmPwd attribute. However the admin password is not being updated on the macbook locally. 

Log stating "unable to connect to local directory or change password. Exiting.... "

bash-3.2$ sudo /usr/local/laps/macOSLAPS -resetPassword
Info|Wed Jan 16, 2019 12:00:33 PM|macOSLAPS|Password Change is required as the LAPS password for admin has expired
Info|Wed Jan 16, 2019 12:00:33 PM|macOSLAPS|Password change has been completed for local admin admin. New expiration date is Sun Mar 17, 2019 12:00:33 PM
Error|Wed Jan 16, 2019 12:00:33 PM|macOSLAPS|Unable to connect to local directory or change password. Exiting...
bash-3.2$

**Comment by Edwinterb** [comment]
@ffxsup I believe your issue is the same as issue https://github.com/joshua-d-miller/macOSLAPS/issues/22

**Comment by joshua-d-miller** [comment]
Closing as this is a duplicate issue
