### ISSUE TITLE
macOSLAPS binary not running - signing certificate revoked

### ISSUE THREAD

**Issue by neilmartin83** [joshua-d-miller/macOSLAPS#34]
Have started seeing the following crash when running the macOSLAPS binary:

```
$ macOSLAPS 
Killed: 9
```

A bit of further digging:

```
$ codesign -vvv /usr/local/laps/macOSLAPS
/usr/local/laps/macOSLAPS: CSSMERR_TP_CERT_REVOKED
In architecture: x86_64
```

Corroborated with @howlerwolf1313 on the MacAdmins Slack in the #macoslaps channel

This is with the current 1.1.1 release, build 223

**Comment by joshua-d-miller** [comment]
Please check the latest build :)

**Comment by joshua-d-miller** [comment]
Neil has confirmed this issue has been resolved.
