### ISSUE TITLE
Build not running on macOS prior to 10.14

### ISSUE THREAD

**Issue by chrisleeddotcom** [joshua-d-miller/macOSLAPS#36]
So I deployed and built the package on our Jamf Infrastructure out to all of our endpoints.

All of the Mojave 10.14 machines run without issue.

I noticed today that none of the High Sierra 10.13 machines are checking in with passwords, I turned on debug logging in the plist, found this error..

dyld: Library not loaded: @rpath/libswiftAppKit.dylib
  Referenced from: /usr/local/laps/macOSLAPS
  Reason: image not found

Any help would be greatly appreciated.

**Comment by joshua-d-miller** [comment]
@neutch I tested the 1.1.4 package under releases on a 10.13 machine today and it seems to work. Please keep in mind that if you are running a previous version that there was a build that was built without the Swift libraries and future packages will also be built without the libraries.

**Comment by chrisleeddotcom** [comment]
So I am downloading the latest zip from the releases and I'm seeing the following.. perhaps the zip on the releases page is the wrong version? I'm still seeing the same issues with this project..
<img width="493" alt="image" src="https://user-images.githubusercontent.com/1381147/63596396-2dbc0900-c589-11e9-89c3-9dc648413f3c.png">

**Comment by joshua-d-miller** [comment]
@neutch I tested the 1.1.4 package under releases on a 10.13 machine today and it seems to work. Please keep in mind that if you are running a previous version that there was a build that was built without the Swift libraries and future packages will also be built without the libraries.

**Comment by joshua-d-miller** [comment]
@neutch Any luck with the 1.1.4 PKG?

**Comment by joshua-d-miller** [comment]
@neutch,

I haven't heard from you in a while. If you are still having issues please feel free to reach out to me directly or to contact me on the MacAdmins slack in the #macoslaps channel.

Thanks!
