### ISSUE TITLE
Binary from PKG and missing plist files

### ISSUE THREAD

**Issue by iamoverrated** [joshua-d-miller/macOSLAPS#37]
After installing the binary, there wasn't a plist file created in /Library/Preferences.  I have no idea where the plist file needs to go.  I've tried manually adding them to /Library/Preferences but the application won't read any of the settings.  Any help would be appreciated.

**Comment by joshua-d-miller** [comment]
@iamoverrated Did you use the PKG installer under releases? This will install the binary and the plist file as well as a way to call macOSLAPS from the terminal if needed.

**Comment by joshua-d-miller** [comment]
@iamoverrated,

Please use the package installer which should give you everything you need. The plist file should be created with either the **defaults** command in /Library/Preferences or you can use MDM to create the PLIST file which will live in /Library/Managed Preferences.

Thanks!
