### ISSUE TITLE
RemovePassChars question

### ISSUE THREAD

**Issue by Liampowe** [joshua-d-miller/macOSLAPS#41]
defaults write /Library/Preferences/edu.psu.macoslaps RemovePassChars -string []!~_“|<>,\/{}^'
Is what I have set to not use those symbols. The problem is I think the ' is causing problems with the script.

I get this error.Line 4: unexpected EOF while looking for matching `''

Thanks for any help.

**Comment by Edwinterb** [comment]
have you tried:
`defaults write /Library/Preferences/edu.psu.macoslaps RemovePassChars -string "[]!~_“|<>,/{}^'"`

**Comment by Liampowe** [comment]
Thought I did. But looks like I double double quoted it using Atom. Thanks for the info.
