### ISSUE TITLE
dyld: Library not loaded: @rpath/libswiftCore.dylib error when running macOSLAPS command

### ISSUE THREAD

**Issue by pticyn** [joshua-d-miller/macOSLAPS#43]
Clean install of High Sierra 10.13.6 (17G65)
macOSLAPS version: 1.1.6
Running macOSLAPS command I'm getting this error:

_$ sudo /usr/local/laps/macOSLAPS
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /usr/local/laps/macOSLAPS
  Reason: image not found
Abort trap: 6_

**Comment by joshua-d-miller** [comment]
Since you are on macOS High Sierra you will need to download the Swift Binaries Package as that is now required for older versions of macOS. You can get it here and it should resolve your issue: https://support.apple.com/kb/DL1998?locale=en_US. Please let me know if this works for you.

**Comment by pticyn** [comment]
> Since you are on macOS High Sierra you will need to download the Swift Binaries Package as that is now required for older versions of macOS. You can get it here and it should resolve your issue: https://support.apple.com/kb/DL1998?locale=en_US. Please let me know if this works for you.

Yes, that worked.
Thanks
