### ISSUE TITLE
How to change the admin account managed by macOSLAPS

### ISSUE THREAD

**Issue by jaireimy** [joshua-d-miller/macOSLAPS#58]
Hello,

this is not really an issue but I didn't know where to ask for help. I am trying to start to use your tool on my company Macbooks, but I can't find a way to change the admin account that will be managed, from "admin" to something else.
Sadly I don't have a MDM solution to generate a plist file either.

Please note that I am not very familiar to MacOS, so my question might be dumb, but still, I am strugging :)

I tried to manually edit the plist file with text editor but it says that I don't have sufficient permission to do any change, even if I am myself admin.

The most simple workaround I found was to create an "admin" account but we are used to use another account name. Also I think its best to use a less obvious account name for admin.

 So this is not a big deal but for the sake of understanding how this work, any help would be appreciated.

**Comment by tauthement** [comment]
You may need to use sudo. So you would do something like: "sudo vim /path/to/file".

**Comment by jaireimy** [comment]
Hey, finally after testing on another device I didn't have a plist created at all. I used these commands to get it done with the settings I needed:

sudo defaults write /Library/Preferences/edu.psu.macoslaps LocalAdminAccount “accountname”
sudo defaults write /Library/Preferences/edu.psu.macoslaps FirstPass "CurrentAccountPassword" 

That would be great to add this information in the Github page for people not used to manage plist :)
Also this solution is only if you don't use MDM.
