### ISSUE TITLE
Illegal instruction: 4

### ISSUE THREAD

**Issue by DorianBorca** [joshua-d-miller/macOSLAPS#59]
Testing macOSLAPS 2.1.0 on Mac OS Big Sur, installed via the .pkg and keep getting above message. Tried different configurations within the edu.psu.macoslaps.plist file but all return the same result. Only time when it does not print that message is when passing the "-version" flag. Any help would be much appreciated. Thank you

**Comment by joshua-d-miller** [comment]
Hello @DorianBorca!

Please make sure you have the latest 2.1.0 build as PSU revoked my signing certificate for the first build of 2.1.0. Let me know if that helps.

Thanks!

**Comment by joshua-d-miller** [comment]
Hello @DorianBorca!

I'm going to go ahead and close this issue as I have not heard back whether the new 2.1.0 packaged version was helpful. Depending on testing in the #macoslaps Slack channel 2.2.0 is around the corner :)
