### ISSUE TITLE
Versions in the pkg receipt/binary are the same for different builds

### ISSUE THREAD

**Issue by neilmartin83** [joshua-d-miller/macOSLAPS#63]
Hi Josh,

We're having trouble pushing updates for macOSLAPS to managed Macs with Munki as the version info is the same for different builds 716 and 721.

Would it please be possible to release 721 as a new version (e.g. 2.1.1) or change the version numbering scheme to 2.1.0.721 to incorporate the build number?

Thank you!

**Comment by joshua-d-miller** [comment]
Hello @neilmartin83,

I sent you a message on the MacAdmins Slack. You definitely bring up a good point and I think this will be the method going forward. Unfortunately the drastic change from build 716 to 721 was a revocation of my signing cert from my previous employer. I have now done my own signing cert to avoid this in the future. I'll be sure to send you a test build when I get time.

Thanks!

**Comment by neilmartin83** [comment]
Heya,

Thank you! We're able to mitigate the issue by removing the quarantine bit and re-setting permissions/ownership, where this version is installed already.

**Comment by joshua-d-miller** [comment]
Hello @neilmartin83!

New build 3.0.0 in prerelease should take care of this issue. Please give it a try and let me know: https://github.com/joshua-d-miller/macOSLAPS/releases/tag/3.0.0(752)

**Comment by joshua-d-miller** [comment]
Latest Binary should address this 3.0.2
