### ISSUE TITLE
/etc/paths.d/laps permission issue

### ISSUE THREAD

**Issue by franton** [joshua-d-miller/macOSLAPS#71]
Hi,

Whenever I open Terminal.app, I see this:

`Last login: Mon Mar 28 16:18:56 on ttys000
laps: Permission denied
user@computer ~ %`

This is due to the file looking like this:

`user@computer paths.d % ls -al
total 16
drwxr-xr-x   4 root  wheel   128 Mar 21 15:13 .
drwxr-xr-x  81 root  wheel  2592 Mar 28 15:52 ..
-rwxr-xr-x   1 root  wheel    23 Jan 18 13:50 100-rvictl
-rwx------   1 root  wheel    15 Dec  3  2019 laps
`

The laps file should have chmod 755 instead of 700 to stop the permission denied error occurring when loading Terminal.

**Comment by joshua-d-miller** [comment]
Hi there!

I'll be sure to take care of this. Hopefully either this evening or maybe this weekend.

Thanks!

**Comment by nmasi324** [comment]
Was this ever corrected? I am seeing this as well.

**Comment by joshua-d-miller** [comment]
This should be addressed in the latest release candidate of 3.0.1. Let me know if it addresses it. Thanks!

**Comment by joshua-d-miller** [comment]
This has been corrected in 3.0.2. Please use the latest release.
