### ISSUE TITLE
Error: macOSLAPS|Unable to retrieve password from macOSLAPS Keychain entry

### ISSUE THREAD

**Issue by Rorzzer** [joshua-d-miller/macOSLAPS#73]
macOS 12.3.1
M1 MacBook Pro
Config Profile below deployed via JAMF

<img width="312" alt="Screen Shot 2022-05-13 at 11 59 22 am" src="https://user-images.githubusercontent.com/26126712/168196264-c3dd5b99-7ace-4a9d-8e83-d57cea05f3b0.png">

**Comment by Rorzzer** [comment]
manually running the command: sudo /usr/local/laps/macOSLAPS -resetPassword
gives the following result

<img width="1079" alt="Screen Shot 2022-05-13 at 12 19 15 pm" src="https://user-images.githubusercontent.com/26126712/168198539-3ef9feae-6519-4f60-85e3-fbdeedd40295.png">

**Comment by Rorzzer** [comment]
Is this the expected function? Can I ignore the above error until the first password reset?

**Comment by joshua-d-miller** [comment]
So the first run should reset the password as one does not exist. Please try the latest release candidate and let me know if it resolve the issue.

**Comment by mrmte** [comment]
im experiencing the same issue and using the latest version

**Comment by joshua-d-miller** [comment]
Thank you for letting me know. I believe I have found the issue and will be releasing another pre release build soon.

**Comment by joshua-d-miller** [comment]
This has been corrected. The issue was the `Local` method was not changing the password if it had never been changed. Please use the 3.0.2 release of macOSLAPS.
