### ISSUE TITLE
macOSLAPS AAD

### ISSUE THREAD

**Issue by crofmmv** [joshua-d-miller/macOSLAPS#77]
Hi we don't have an on prem AD and our macOS are not bound to a domain. the macOS hosts use Jamf Connect for AAD logins but we still have a local admin account, does macOSLAPS work with AAD?

**Comment by joeschlimmer-ic** [comment]
Azure AD is not AD, it doesn't support the extensions needed for a LAPS env.

However, if you use jamf for your MDM, this can write the local password to an extension attribute in Jamf Pro. Not ideal but it is works.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Crawford ***@***.***>
Sent: Saturday, June 11, 2022 4:14:47 PM
To: joshua-d-miller/macOSLAPS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [joshua-d-miller/macOSLAPS] macOSLAPS AAD (Issue #77)

This message originated from outside the Ithaca College email system.


Hi we don't have an on prem AD and our macOS are not bound to a domain. the macOS hosts use Jamf Connect for AAD logins but we still have a local admin account, does macOSLAPS work with AAD?

**Comment by crofmmv** [comment]
I see thanks for your reply, would macOSLAPS work with an admin account that was created during setup Assistant on an Apple Silicon(M1) device?

**Comment by crofmmv** [comment]
So I've got the following so far;

macLAPS pkg deployed 
macLAPS PList Config we are using the Method Local as we don't have AD.

I can run macLAPS on the device for the first time that has both deployed to it.

both the macOSLAPS password and expiration files are in the /private/bar/root/Library/Application folder but how to I get them up to Jamf Pro?

Regards,

Crawford

**Comment by joshua-d-miller** [comment]
Hello @crofmmv,

Those files are temporarily created. The next run will remove them. You would need to create an extension attribute in Jamf to send the password to Jamf. You can see the examples here: https://github.com/joshua-d-miller/macOSLAPS/blob/master/jamf%20Extension%20Attributes/Password:Expiration%20Combined.sh

**Comment by joshua-d-miller** [comment]
Hello @crofmmv,

Wanted to check in and see if you feel submitting the password to Jamf is acceptable over Azure AD.

Thanks!
