### ISSUE TITLE
macOS Ventura pops up with login item added 

### ISSUE THREAD

**Issue by mrmte** [joshua-d-miller/macOSLAPS#79]
<img width="375" alt="Screenshot 2022-09-14 at 11 52 55" src="https://user-images.githubusercontent.com/2095960/190238136-19b8216d-c534-41f7-ba6d-345f7619ec45.png">
any way to suppress this. People will think their system has been hacked.

**Comment by joshua-d-miller** [comment]
This is something I'm currently looking into. Since I am the Developer it is accepted behavior. Please see #75 for more detail. I'm hoping Beta 8 resolves this.

**Comment by richardpurves** [comment]
Tim,

This is something that you need to do yourself. However you'll need to check the private channels as Ventura is still currently NDA.

**Comment by tkimpton** [comment]
Yes I know that. Point being ….that the name should be changed to something less cryptic than the Joshua Miller as if a pop up does appear and it isn’t controlled as it should be with a profile, then it won’t look like malware and cause helpdesk tickets.

**Comment by joshua-d-miller** [comment]
Hello @tkimpton. Have you tried the 3.0.2 pkg? It should negate the popup but it will still show in Login Items as it goes by the Developer Certificate.

**Comment by tkimpton** [comment]
Not yet as I was replying to the ominous response to my issue raised insinuating I was clueless on on Ventura. I will test this when I have a free moment. Thanks

**Comment by EmptyRecord** [comment]
Joshua, on Ventura still the popup was showing with your name on version 2.1.0 and 3.0.2 also.

**Comment by tkimpton** [comment]
Pls ensure your name doesn’t pop up but says something like macOSLAPS instead. Yes we know Ventura R Prurves. Yes we are aware on login items! This is to negate a scenario where a machine may not get a profile to whitelist it!

**Comment by franton** [comment]
So what you're saying @tkimpton is you want @joshua-d-miller to register another Developer ID in the name of macOSLAPS, go through all of Apple's developer identification process but for business (including potentially a DUNS check) then resign everything and at cost to himself? That's pretty unreasonable at best.

BTW I found your own reply semi insulting as well. Considering we've been personal acquaintances in the past and got on well, I don't know where the attitude suddenly comes from. Don't call me out like that again.

**Comment by tkimpton** [comment]
@franton likewise for you calling me out the first place! If you don’t have anything constructive on the issue logged please refrain from commenting further. Good day!

**Comment by tkimpton** [comment]
@franton Apologies. It is still an open issue if not negated the pop up makes end users think they have their system hacked in some way.

**Comment by tkimpton** [comment]
Closing as already highlighted in #75 apologies.
