### ISSUE TITLE
Update json manifest for v3

### ISSUE THREAD

**Issue by staze** [joshua-d-miller/macOSLAPS#84]
Probably an easy one. Just an update to the json profile manifest for v3 of macOSLAPS. 

v2 is here: https://github.com/Jamf-Custom-Profile-Schemas/joshua-d-miller-schemas/blob/master/edu.psu.macoslaps.json

**Comment by joshua-d-miller** [comment]
JSON manifest should now be updated. Let me know if anything is missing.

**Comment by staze** [comment]
Thank you sir! Only thought is should "Method" be a selection rather than string?
