### ISSUE TITLE
Version shows as 3.0.2 instead of 3.0.3 Build 778

### ISSUE THREAD

**Issue by davidbpirie** [joshua-d-miller/macOSLAPS#87]
The new package name indicates v3.0.3, but the Release title is 3.0.2 Build 778 and Info.plist has had the CFBundleVersion updated (778) but not the CFBundleShortVersionString.

**Comment by staze** [comment]
I think the package might actually be 3.0.2 and not 3.0.3, because just installed "3.0.3" and -version still says permission denied.

**Comment by joshua-d-miller** [comment]
Please try the 3.0.4 build as you are correct I did not update the build in the binary.

**Comment by davidbpirie** [comment]
That fixed it for me - thanks!
