### ISSUE TITLE
Case-insensitive command line flags

### ISSUE THREAD

**Issue by dechkovanen** [joshua-d-miller/macOSLAPS#89]
There seems to be a number of failures due to incorrect case in CL flags such as -getPassword around the Internet.

To mitigate these, macOSLAPS should accept flags regardless of the letter case. I don't see any particular reason why **-getPassword**, **-GetPassword** and **-getpassword** should qualify as three different flags.

**Comment by joshua-d-miller** [comment]
Currently testing this and will hopefully change this soon.

**Comment by joshua-d-miller** [comment]
This is currently available in the latest prerelease. Please give it a shot and let me know. Thanks!

**Comment by joshua-d-miller** [comment]
Closed at this has been implemented in 4.0.0 prerelease
