### ISSUE TITLE
Version Extension Attribute

### ISSUE THREAD

**Issue by fgs2022** [joshua-d-miller/macOSLAPS#90]
Do you have a version extension attribute script to use in Jamf so machines can easily update from 3.0.1 to 3.0.4? Thanks.

**Comment by joshua-d-miller** [comment]
Hello @fgs2022,

Here is a simple script that should accomplish that for you:

```
#!/bin/zsh
## Get macOSLAPS Version ##
VERSION=$(/usr/local/laps/macOSLAPS -version)
/bin/echo "<result>$VERSION</result>
```

**Comment by fgs2022** [comment]
Is this all I should need to do?

![image](https://user-images.githubusercontent.com/125387832/221911533-9a3be240-0845-48b6-92df-e1e49c0dedbd.png)

I don't see anything populating even though I've updated inventory multiple times.

<img width="356" alt="image" src="https://user-images.githubusercontent.com/125387832/221911875-ad87c230-60ad-46f2-925f-c90deb93487c.png">

**Comment by joshua-d-miller** [comment]
Hello,

Yes that should be it. Let me know how it goes.

Thanks!

**Comment by fgs2022** [comment]
Unfortunately it is not reporting any version number.

**Comment by fgs2022** [comment]
Would there be any harm in just pushing the latest client out to all endpoints that have macOSLAPS installed, even if they already have the latest version installed?

**Comment by joshua-d-miller** [comment]
```shell
sudo /usr/local/laps/macOSLAPS -version
3.0.4
```

You can update LAPS as much as you want. You could also look for the pkg recipes and verify that with this command:

```shell
pkgutil --pkg-info "edu.psu.macOSLAPS" | grep "version" | awk '{print $2}'
3.0.4
```
